### ISSUE TITLE
doc.body is undefined

### ISSUE THREAD

**Issue by flying-sheep** [adam-p/markdown-here#237]
in makeRequestToPrivilegedScript, neither doc.head nor doc.body exist, resulting in exception flood.

**Comment by adam-p** [comment]
Can you check another thing? Go into your `about:config` page, search for "markdown-here" and share a screenshot of the results. Thanks.

I'm now experiencing the same problem you had, and it seems to be be due to `extensions.markdown-here.services.sync.prefs.sync.extensions.markdown-here.*`. Those shouldn't exist at all. They should instead be `services.sync.prefs.sync.extensions.markdown-here.*`. (I have both forms.)

So, if you *do* have config entries that start with ``extensions.markdown-here.services.sync.prefs.sync.extensions.markdown-here.`, then the fix (or at least workaround) is to delete them.

**Comment by adam-p** [comment]
I believe I fixed this problem in 89359f083387952f0de3ca8142055359a1c4d264. But I would still really appreciate a screenshot of your "markdown-here" results in `about:config`, because I don't understand how you could have gotten into the bad state.

(It happened to me only by fooling around with test code.)

**Comment by flying-sheep** [comment]
idk if this was the PC where it happened, but here you go:

![md-here](https://cloud.githubusercontent.com/assets/291575/6431394/4960afc2-c02e-11e4-84fd-b5b10eb79e99.png)

**Comment by adam-p** [comment]
@flying-sheep: Thanks. I can't see anything there what would cause the problem. So maybe it was a different computer? Anyway, hopefully the fix in the next release will sort out your problem.
