### ISSUE TITLE
Long delay until render in Chrome Beta and Canary

### ISSUE THREAD

**Issue by bornio** [adam-p/markdown-here#241]
When using Chrome, I have a long delay until the render finally happens.
This happens even in MDH's "options" page, but not on the website where it is instant.

Safari doesn't have this issue for me.

This how some of the JS profile looks:

```
8660.0 ms99.45 %	8660.0 ms99.45 %	(idle)	
15.0 ms0.17 %	15.0 ms0.17 %	(program)	
4.0 ms0.05 %	5.0 ms0.06 %	extensions::unc…ion_handler:62getStackTrace	
4.0 ms0.05 %	20.0 ms0.23 %	Apply	
2.0 ms0.02 %	2.0 ms0.02 %	utils.js:112walkDOM	
2.0 ms0.02 %	2.0 ms0.02 %	extensions::unc…ion_handler:62getStackTrace	
2.0 ms0.02 %	2.0 ms0.02 %	setAttribute	
1.0 ms0.01 %	1.0 ms0.01 %	highlight.js:325startNewMode	
1.0 ms0.01 %	1.0 ms0.01 %	marked.js:149Lexer.token	
1.0 ms0.01 %	1.0 ms0.01 %	utils.js:255getDocumentFragmentHTML	
1.0 ms0.01 %	1.0 ms0.01 %	options-store.js:148(anonymous function)	
1.0 ms0.01 %	5.0 ms0.06 %	markdown-render.js:28markdownRender	
1.0 ms0.01 %	1.0 ms0.01 %	jsHtmlToText.js:26htmlToText	
1.0 ms0.01 %	3.0 ms0.03 %	extensions::messaging:311dispatchOnMessage	
1.0 ms0.01 %	1.0 ms0.01 %	marked.js:807Renderer.heading	
1.0 ms0.01 %	2.0 ms0.02 %	options.js:191checkChange	
1.0 ms0.01 %	1.0 ms0.01 %	extensions::json_schema:236JSONSchemaValidator.validate	
1.0 ms0.01 %	1.0 ms0.01 %	get value	
1.0 ms0.01 %	1.0 ms0.01 %	marked.js:562InlineLexer.output	
1.0 ms0.01 %	3.0 ms0.03 %	markdown-here.js:255makeStylesExplicit	
1.0 ms0.01 %	1.0 ms0.01 %	utils.js:979strToUTF8Arr	
1.0 ms0.01 %	1.0 ms0.01 %	utils.js:932base64EncArr	
1.0 ms0.01 %	1.0 ms0.01 %	createContextualFragment	
1.0 ms0.01 %	6.0 ms0.07 %	extensions::SafeBuiltins:10target.(anonymous function)	
1.0 ms0.01 %	1.0 ms0.01 %	extensions::unc…ion_handler:62getStackTrace	
1.0 ms0.01 %	1.0 ms0.01 %	utils.js:88cleanAttributes	
0 ms0 %	6.0 ms0.07 %	utils.js:578nextTickInner	
0 ms0 %	2.0 ms0.02 %	options.js:252requestMarkdownConversion	
0 ms0 %	1.0 ms0.01 %	extensions::messaging:216dispatchOnConnect	
...
```

**Comment by adam-p** [comment]
Can you give me an order of magnitude for "long delay"? 

Is this just with normal-ish length MD?

What other extensions do you have installed? Can you try with a fresh Chrome user profile? (Or with [Chrome Canary](https://www.google.com/chrome/browser/canary.html), which can be installed independently from release Chrome.)

**Comment by bornio** [comment]
This happens after a while, even after a complete fresh install of Chrome.
It happens every time, but I haven't found how to reproduce it on-demand. :disappointed:

**Comment by adam-p** [comment]
So this is for email content of any length? Jeez.

What OS and Chrome version are you running?

**Comment by adam-p** [comment]
@bornio: I found a slowdown in Chrome Canary (due to a throttling of `setTimeout`). I created a test build that I'd like you to try to see if it solves your problem. You can find it here:
https://chrome.google.com/webstore/detail/markdown-here-test/enihccblfeliefaickgkbpfeeakjdffh

Please let me know if that renders quickly for you.

**Comment by adam-p** [comment]
Here's the same test that the test extension provides, but maybe easier -- depending on how comfortable you are with the Chrome console.

Go into the [background scripts console](https://github.com/adam-p/markdown-here/wiki/Troubleshooting#inspecting-background-scripts) and paste this JavaScript:

```js
var start = new Date(); setTimeout(function() {console.log('t1', new Date() - start)}, 0); setTimeout(function() {console.log('t2', new Date() - start)}, 0);
```

What are the numbers after `t1` and `t2`? If they're in the high hundreds, then we know what the problem is.

But... I only get this behaviour with Chrome Canary and not with regular Chrome. So...?

**Comment by bornio** [comment]
@adam-p On the "regular" version my numbers are between jumping between `900` and `300`. The configuration page takes roughly 8 seconds to render – reproduced multiple times.

The good news is that your test build works great!! :bow: 

BTW, I am running Chrome version 43.0.2357.52 beta (64-bit), on OSX 10.10.3.
