### ISSUE TITLE
[feature request] different list styles

### ISSUE THREAD

**Issue by r2evans** [adam-p/markdown-here#254]
Though not standard across all markdown (or CommonMark) "standards" [sic], one feature that [pandoc](http://pandoc.org) offers is different numbering styles for lists. For example, in addition to the default `1, 2, 3`, it also supports `a, b, c, ...` and `i, ii, iii, iv, ...`. Additionally, it can have a dot after it (`1.`, the default), but it also allows parentheses (`(ii)`)  and a right parenthesis (`3)`).

Is there a chance either or both alternate numbering schemes can be added to MDH's parsing?

I've been turning peers to see the light of MDH. Thank you for making/maintaining it!

-bill

**Comment by adam-p** [comment]
Half of what you're asking for is already supported by Markdown Here, and the other half isn't possible. 

The good news: By customizing the "Primary Styling CSS" in the MDH options you can change the list numbering style. I actually plan on changing the default in the next release to match what Github does (number then alpha then roman). Like so:

```css
ol ol,
ul ol {
  list-style-type: lower-alpha;
}

ul ul ol,
ul ol ol,
ol ul ol,
ol ol ol {
  list-style-type: lower-roman;
}
```

You can also have Greek letters and [many others](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type). (As of a few days ago, this info is in our [Hints and Tips](https://github.com/adam-p/markdown-here/wiki/Tips-and-Tricks#different-numbering-for-ordered-lists) wiki page.)

The bad news: You [can't use CSS pseudo-classes inline](http://stackoverflow.com/a/5293299). And [pseudo-classes are needed](http://stackoverflow.com/a/1636635) for the parentheses and dots. And MDH needs to use inline classes (because that's how you style email, etc.).

Cool? I'm going to be optimistic and close this issue.

**Comment by r2evans** [comment]
That answers it, thanks!

**Comment by optimsari** [comment]
@r2evans Could you please send me your email to: zad_sim@yahoo.com, I would like to consult you on a problem in optimization using R.
