### ISSUE TITLE
Causes Gmail to hang and show blank tab

### ISSUE THREAD

**Issue by slhck** [adam-p/markdown-here#262]
I'm using Google Chrome Version 41.0.2272.89 (64-bit) with MDH v2.11.4.

I have an existing e-mail thread in Gmail consisting of a few messages where I (as a sender) used MDH in previous mails. They show correctly formatted in the quoted reply.

Now, when I write a reply (using the floating editor or the normal window), then apply the MDH formatting, then click "Send", the button is pressed down, but then the tab hangs. It becomes unresponsive, then the whole tab becomes white, and I have to kill it. I cannot navigate anywhere else. 

When I apply MDH formatting, then un-apply it using the button, the same problem occurs.

After a few minutes, when clicking the `x` on the (non-responsive) tab to close it, I get the prompt:

> There is currently a request to the server pending. You may lose recent changes by navigating away.
Your draft has been modified.

Then, the tab shows normally again, with the draft saved, but the message is (probably) not sent. There are no JS console messages or anything. I can reproduce this every time I reply to that existing mail.

I checked whether I could send using plain-text, and indeed, I could. But then, viewing the sent messages again in Gmail showed this – apparently, one of my earlier trials got through after all:

![image](https://cloud.githubusercontent.com/assets/582444/6657313/f5ea618c-cb48-11e4-8d74-b3ba787443da.png)

Very weird, all this.

**Comment by adam-p** [comment]
Weird/horrible. If you disable the "forgot-to-render" check in the MDH options, does it allow you to send?

**Comment by slhck** [comment]
Hm, that was never enabled. I enabled it now and I'll do some further tests this evening.

**Comment by adam-p** [comment]
Enabling forgot-to-render can only make things worse, as it does additional processing when you attempt to send the email. I was hoping it would somehow be the cause of the problem.

I don't have any answers, but maybe I can provide some more info and think of more questions...

The `<div title="MDH:...>` you see at the bottom of the screenshot: That's where Markdown Here keeps the original Markdown, base64-encoded. There's one of those at the bottom of every message you MDH-render, and it's usually hidden. It's hard to tell from your screenshot, but... The reason you're seeing it is probably because the message has gotten too long for Gmail to display inline. Gmail only displays X(?) bytes inline in the conversation view, and then truncates the message and provides a link at the bottom that says "[Message clipped] View entire message". If the truncation happens to fall in the middle of that hidden raw-MD-div, then the styling that hides it bets messed up and you can see it.

I have tried two tests without being able to reproduce the problem: 

1. I created a "conversation" (reply chain) of about 25 emails that are MDH-rendered. No problems.
2. I wrote a big long email that triggered the truncation inside the original-MD-div (by pasting the MDH README twice in a single email). Then I replied to it. No problems.

How many replies are in your conversation? How large-ish are your messages? Maybe I wasn't reproducing your environment sufficiently.

One other thing you can look at: In Chrome, Shift+Esc brings up the "task manager" (you can also get to it with the menu button --> More Tools --> Task manager). Sort by CPU or memory and see what's spiking. I'm not sure how much info there will be.

In the Chrome Dev Tools (console stuff) you could try profiling. Of course, if the whole thing crashes you might not get much. (I can't really guide you with this, since I don't really know how to use it.)

To make sure that it really *is* MDH causing the problem, you could disable the extension, reload the Gmail tab, and then try sending.

If you have a non-sensitive email chain that reproduces the problem you could forward it to me: pritchard.adam@gmail.com

**Comment by slhck** [comment]
I tried it on a new conversation and couldn't repro it. Then I tried replying to myself on the old thread and I couldn't repro it either.

I had ~20 messages, not too long, a few paragraphs maybe.

I'll close this for the time being and I'll write back if it occurs again.

Thanks for your efforts!

**Comment by adam-p** [comment]
Cool, thanks.

**Comment by ait-jorismak** [comment]
_huge_ necro-posting this (5 years almost),

but the huge base64 included 'hidden div' happens with inline images (at my side anyway). The original-markdown-div gets very huge and gmail truncates it in a bad way .. clicking 'show entire message' displays it normally.
