### ISSUE TITLE
Fastmail signature detection not working

### ISSUE THREAD

**Issue by alexandru** [adam-p/markdown-here#273]
Markdown-here does not detect signatures in Fastmail's web interface. This is because the detection relies on the presence of `'-- '` and Fastmail strips that needed whitespace caracter at the end.

**Comment by adam-p** [comment]
I see what you mean. It sure is annoying that the plain-text compose box has the trailing space, but the rich-text compose doesn't.

**Comment by adam-p** [comment]
Workaround: It's only the *default* sig that's broken -- you can go into the Fastmail settings and add a space at the end of the signature separator to fix it.

I added this info to the [Compatibility wiki](https://github.com/adam-p/markdown-here/wiki/Compatibility#fastmail). I'm going to close this issue since the workaround is so solid.

![fastmail-sig-edit-smaller](https://cloud.githubusercontent.com/assets/425687/7448214/c4b09126-f1e1-11e4-8bc1-3063c44081cf.gif)
