### ISSUE TITLE
MDH + Blackboard Learn

### ISSUE THREAD

**Issue by antonio-gil** [adam-p/markdown-here#293]
Hi, good afternoon

I was today testing the use of MDH on the platform [Blackboard Learn](https://en.wikipedia.org/wiki/Blackboard_Learn) (or, the [official site](http://www.blackboard.com/), which is currently (as July 16 2015, 12:58 GMT -6) throwing a 500 error), and it's working (almost) fine.

I say *'almost'* because I've found that on some text editors of the platform MDH doesn't work at all, and on other text editors it work as expected (***weird***).

The only thing that is not working (on the text editors where MDH works) is the contextual menu, and I think that is because such text editors have their own behavior for contextual menu (independent from the browser's behavior).

I was testing (again) with Opera 30.0.1835.125, and using this time the example text that [Dillinger.io](http://dillinger.io) uses.

Later I'll check with Google Chrome, and Firefox to see if the issue of the text editors is general, or is a Opera related thing.

(P.S. I'm the same Antonio Gil who reported the functionality on Protonmail, just I wasn't aware that I can post here).

Regards.

**Comment by adam-p** [comment]
I'll add mention of this to the [Compatibility wiki page](https://github.com/adam-p/markdown-here/wiki/Compatibility) (which isn't publicly editable, because there was too much defacing of the cheatsheet).

On pages that have their own context menu, you can often get the default browser right-click menu by holding the Shift key as you right-click. (Although I'm not sure what that will prove, since no normal user would do that.)

A good source of sample MD for testing MDH is from the MDH Options page, in the Preview panel. Unrender it back to raw MD, then copy-paste it (with a [plaintext paste](https://github.com/adam-p/markdown-here/wiki/Tips-and-Tricks#pasting)). Note, however, that pasting isn't necessarily the same as typing. In particular, the newlines you get from pasting might not be the same -- sometime you get `<br>` elements as newlines instead of `<p>`. (When I test I have an AutoHotKey script that pastes by typing out the clipboard content.)

When MDH doesn't work at all are you getting the error message "The selected field is not valid for Markdown rendering"?

If the rendering is getting messed up, you can take a look at the HTML being produced. I made some animated GIFs a while ago that kinda-sorta tell you how to do that: https://github.com/adam-p/markdown-here/wiki/Troubleshooting#reporting-and-debugging

**Comment by adam-p** [comment]
I'm going to close this issue, but feel free to add any more info you find to it -- I have linked to it from the Compatibility wiki page, so interested people will come here for details.
