### ISSUE TITLE
Newline added when toggling back and forth between markdown preview and edit mode in gmail

### ISSUE THREAD

**Issue by joelostblom** [adam-p/markdown-here#295]
Hi,
When I am using Markdown Here (v2.11.8) for authoring gmail messages and switch back to edit mode after previewing, a newline is added on the top of the message. Keeping switching back and forth between preview and edit causes one more newline to be added each time, pushing the text of the message downwards.

I didin't experience this behavior when I tested on a couple of other sites so maybe the problem is gmail specific. I am using gmail in a separate app window on Ubuntu 15.04, Chromium 43.0.2357.130.

**Comment by adam-p** [comment]
Do you use a custom font? See #236

**Comment by joelostblom** [comment]
Nope, I use the standard gmail sans serif font.

**Comment by ianjanicki** [comment]
I have the same problem. Using unformatted font. Mine does not push the text farther down the page with each toggle as @joelostblom describes, it just consistently pushes the text to the second line with each toggle. 

When I put my cursor at the beginning of my rendered message and try to press delete to remove the line, it does not allow me to do so. It's like there is a frozen line in the rendered view.

Screencast: https://www.dropbox.com/s/bnhnncypo1dff20/markdown%20here%20bug.mov?dl=0

**Comment by adam-p** [comment]
@ianjanicki: The single empty line was fixed with #243. For the fix to take effect, you need to [reset your Primary Styling CSS](https://github.com/adam-p/markdown-here/wiki/Troubleshooting#getting-the-latest-primary-styling-css).

@joelostblom: Can you capture the HTML of your message both before and after rendering, and after rendering multiple times? An explanation of how to copy the HTML is [shown here](https://github.com/adam-p/markdown-here/wiki/Troubleshooting#copying-html).  Thanks.

**Comment by joelostblom** [comment]
Every time I untoggle Markdown Here, the following segment is added before the raw message:
`<div class="gmail_default" style="font-family: arial, helvetica, sans-serif;">​​</div>`

After toggling back and forth a few times, I end up with the html shown in the image below. The message is in the very last segment.
![image](https://cloud.githubusercontent.com/assets/4560057/9457427/331b24ba-4ab0-11e5-8869-349510304c12.png)

Curiously, this behaviour is only present when using the shortcut Ctrl-Alt-m to toggle Markdown Here. When I right click and toggle no newline is added.

**Comment by joelostblom** [comment]
Just reproduced this behavior on another computer running Windows 10 and Chrome.

**Comment by adam-p** [comment]
I'm pretty sure you have Gmail configured to use a specific font. You can disable it by going into the Gmail settings and clicking this button:

![image](https://cloud.githubusercontent.com/assets/425687/9949784/d7f35ff2-5d7f-11e5-8d2a-11ffeb7166c4.png)

Like, you're using the basically-default sans-serif font, but it's still configured, rather than the actual "no specific font" default. Try disabling it and seeing if the blank line thing still happens.

**Comment by joelostblom** [comment]
Ah ok, you are right. After clicking 'remove formatting' and saving it works even though it still says I am using Sans Serif and the text looks the same. Thanks!
