### ISSUE TITLE
Syntax for internal links in Wiki not compatible with CommonMark

### ISSUE THREAD

**Issue by tloredo** [adam-p/markdown-here#424]
This is a possible issue with the Wiki, not with markdown-here, but I don't know where else to post it. My apologies if it's inappropriate here.

I've modeled some of my Markdown documents on the Markdown and Markdown-here cheatsheets, which use this syntax for the target for internal links (for example, from `(#docs)` in a table of contents:

```
<a name="docs"/>
## Documentation
```

I've used this for Markdown cells stored in the Quiver programmer's notebook (for Mac). After a recent update, rendering of these notebooks fails. The links work, but `## Documentation` appears as raw text, not rendered as a heading.

I raised this as a possible regression with the developers, but they indicated it is intended behavior. They recently changed their parser to Markdown-it, which tries to adhere to CommonMark, which does not support the syntax used in the Wiki cheatsheets.  The supported syntax for a link target is instead:

```
## Documentation <a name="docs"/>
```

Although the cheatsheets use internal links, they don't document them, so this issue is not visible to users who only read them, rather than using their source code as example code. Even so, if the CommonMark syntax is supported by the GitHub parser, it may be worth switching to it.

FYI, the Quiver developers pointed me to this online parser for checking what syntax is compatible with CommonMark:

http://spec.commonmark.org/dingus/

**Comment by adam-p** [comment]
I "fixed" the wiki by putting a blank line between the anchor and the header. After reading the info you gave I decided to change it to be  more correct, but... it doesn't work as well. With the anchor at the end of the line, the scroll-jump goes *below* the header, which I would consider incorrect. So I'm going to leave the anchor above.

I sense that you would like the ToC tricks to be explained in the wiki. I'm torn about doing that, and even more since the CommonMark approach isn't very effective (just on Github? just in the GH wiki?). But, maybe...
