### ISSUE TITLE
GMail (on Firefox) bottom posting code-snippet doesn't render as code

### ISSUE THREAD

**Issue by rakhimov** [adam-p/markdown-here#443]
Instead, it seems to be rendered as ``monospace plain-text``
that is similar to what double back-quotes do.

**Comment by adam-p** [comment]
Do you mean that the code isn't syntax-highlighted? Are you specifying a language? Like so:
````
```js
var i = 0;
```
````

Otherwise, I'm going to need more info. Screenshots, original Markdown, resulting HTML. Some directions for getting the latter here: https://github.com/adam-p/markdown-here/wiki/Troubleshooting#copying-html

**Comment by rakhimov** [comment]
Hmm, it works now. I believe I was trying to put C++ code.
I can't replicate the error anymore on firefox 56.
Will file a better bug report in future. Sorry.
