### ISSUE TITLE
Markdown-Here does not work with Thunderbird 60 Beta

### ISSUE THREAD

**Issue by tehmul** [adam-p/markdown-here#495]
Markdown 2.13.2 is not compatible with Thunderbird 60.0b5 - any nightly/beta build available for TB 60 using webextensions available?

After disabling `extensions.strictCompatibility` , Markdown Here options (Tools>Addon Options>Markdown Here) show up as unclickable text on a transparent background.

**Comment by pmanu93** [comment]
@tehmul You can still use it if you change the `extensions.strictCompatibility` to `false` in preferences > configurations editor

**Comment by tehmul** [comment]
Thanks, pmanu93 - edited the ticket after trying your suggestion.

**Comment by PackElend** [comment]
I installed https://addons.mozilla.org/en-US/thunderbird/addon/markdown-here-xul/ but nothing shows up in the context menu

**Comment by qolii** [comment]
Hm. When I try to install the file `markdown_here-2.13.2-fx.xpi` by dragging it onto the `Add-ons Manager` tab, I get the message `This add-on could not be installed because it appears to be corrupt` in the red bar at the top of the tab.

If I go to the `Debug Add-ons` tab, click `Load Temporary Add-on`, and browse to the xpi file, I get the error message: `There was an error during installation: Install manifest specifies unknown optionsType: 1`.

Both of these occur whether `extensions.strictCompatibility` is `true` or `false`.

How are y'all installing this?

**Comment by tehmul** [comment]
I get the same result as @qolii with the release TB 60 (x86_64 Windows version)

**Comment by dugite-code** [comment]
It looks like Thunderbird doesn't like the `<em:optionsType>1</em:optionsType>` in the install.rdf

Not sure why it's explicitly called as it [defaults to options type 1 anyway](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Install_Manifests#optionsType)

In the error console:
```
1534398647548	addons.xpi	WARN	Invalid XPI: Error: Install manifest specifies unknown optionsType: 1 (resource://gre/modules/addons/XPIInstall.jsm:565:13) JS Stack trace: loadManifestFromRDF@XPIInstall.jsm:565:13
loadFromRDF@XPIInstall.jsm:838:25
loadManifestFromZipReader@XPIInstall.jsm:868:21
loadManifest@XPIInstall.jsm:1533:26
init@XPIInstall.jsm:1999:13
createLocalInstall@XPIProvider.jsm:4821:12
getInstallForFile@XPIProvider.jsm:3513:5
callProviderAsync@AddonManager.jsm:279:12
promiseCallProvider/<@AddonManager.jsm:303:53
promiseCallProvider@AddonManager.jsm:302:10
getInstallForFile/<@AddonManager.jsm:1744:29
getInstallForFile@AddonManager.jsm:1742:13
getInstallForFile@AddonManager.jsm:3453:7
doCommand/<@extensions.js:1348:13
```

**Comment by dugite-code** [comment]
Some more of my research:

Several preferences are not saving this may be because [according to the docs](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIPrefBranch#setComplexValue()) `NsISupportsString` in `setComplexValue()` has been dropped in favour of `setStringPref()`. The dev of awesome auto archive [looks to have a solution](https://github.com/wangvisual/autoarchive/blob/master/src/content/autoArchivePref.jsm#L78)

**Comment by dugite-code** [comment]
I've done some experiments trying to use setStringPref(). Preferences are saved, but syntax styling is not applied.

I also get the following error suggesting I am on the wrong path here:
```
Warning: attempting to write 4478 bytes to preference extensions.markdown-here.main-css. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
```

https://github.com/dugite-code/markdown-here/tree/TB60

**Comment by adam-p** [comment]
@dugite-code Your PR changes are pretty much the same as what I have in progress. Except I have try-and-catch-exception rather than version-check. I prefer yours in principle, but I'm going to have to try it out in Postbox, Icedove, and Pale Moon (which all use the XUL extension, afaik). It might be more client-agnostic and robust to go the exception way.

For the record, here are Mozilla notes about the string pref change:
https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57#Removed_in_mozilla58
And the `optionsType` change:
https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57#Removed_and_changed_in_mozilla59

I also need to test the `optionsType` change. Postbox was never able to access the options page, but Ice Dove and Pale Moon were. 

I might have to make separate builds for some of these clients (or abandon some of them).

**Comment by adam-p** [comment]
Fixed in PR #520. The new version has been submitted to Mozilla. I'll post here again when it's accepted (or you'll just get auto-updated). Be warned that sometimes approval takes a long time (and sometimes it doesn't).

**Comment by adam-p** [comment]
Mozilla review says: "Queue Position: 17 of 25" 

It started out at "19 of 19", so that's less advancement than it seems. If it takes a week to gain 2 positions... you can do the math.

You can get the pre-review extension here: https://addons.thunderbird.net/thunderbird/downloads/file/1011811/markdown_here-2.13.3-tb.xpi

(But caveats about "pre-review" apply. Maybe I did something shady so you should wait for the Mozilla review to clear it.)

**Comment by adam-p** [comment]
Mozilla approved the update just now.
