### ISSUE TITLE
Markdown-here dosen't work with table in bullet list 

### ISSUE THREAD

**Issue by wuseal** [adam-p/markdown-here#521]
This markdown code can't convert well in outlook email and Gmail
```
* #### Table
  | a               | b               |
  | --------------- | --------------- |
  | 1<br>2<br>3<br> | 1<br>2<br>3<br> |
```
Or any thing I missed ? Hope this is not a really bug. thanks

**Comment by wz233** [comment]
coz you add HTML tags like <br> within Markdown's table symbols. 
You can use pure HTML code or Markdown standard to generate a table, but you cannot mix.

**Comment by wz233** [comment]
\<br\>

**Comment by wuseal** [comment]
Em... But `Markdown-Here` works well with this code with HTML code And Markdown mix.
```
#### Table
  | a               | b               |
  | --------------- | --------------- |
  | 1<br>2<br>3<br> | 1<br>2<br>3<br> |
```
Hope it works well with 
```
* #### Table
  | a               | b               |
  | --------------- | --------------- |
  | 1<br>2<br>3<br> | 1<br>2<br>3<br> |
```
too.

**Comment by wz233** [comment]
> Em... But `Markdown-Here` works well with this code with HTML code And Markdown mix.
> 
> ```
> #### Table
>   | a               | b               |
>   | --------------- | --------------- |
>   | 1<br>2<br>3<br> | 1<br>2<br>3<br> |
> ```
> Hope it works well with
> 
> ```
> * #### Table
>   | a               | b               |
>   | --------------- | --------------- |
>   | 1<br>2<br>3<br> | 1<br>2<br>3<br> |
> ```
> too.

Different MarkDown editor has its own way to parse Markdown syntax. Some editors support inline html tags while others may not. The best way is to use your own favourite Markdown editor, enjoy its strength and know its limitations.

**Comment by wuseal** [comment]
@wz233 Nice Answer !

**Comment by wtianyi** [comment]
The same problem occurred to me and my table doesn't have HTML tags inside:

The piece of markdown is like
```
1. The scale of their experiments:
    - As comparison:
| Network       | # parameters |
|---------------+--------------|
| LeNet         |        44426 |
| VGG-11        |      9231114 |
| VGG-19        |     20040522 |
| WideResNet-28 |     36489290 |

2. something else
```

I believe it's due to a known issue of the `marked.js` library used by MDH. See https://github.com/markedjs/marked/issues/811 and https://github.com/markedjs/marked/issues/980

I replaced the old version of `marked.js` with the latest version (https://github.com/markedjs/marked/blob/master/lib/marked.js) and made adaptations (https://github.com/wtianyi/markdown-here/commit/46ff19ef71cf9e9ae3645cd80422c9cdd02f8e37), and now the tables in lists are correctly treated.
